# Generated by Django 4.2.5 on 2023-10-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practice',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='course',
            name='lectures',
        ),
        migrations.RemoveField(
            model_name='course',
            name='practices',
        ),
        migrations.AddField(
            model_name='course',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to='practices/'),
        ),
        migrations.AddField(
            model_name='course',
            name='file10',
            field=models.FileField(blank=True, null=True, upload_to='practices/'),
        ),
        migrations.AddField(
            model_name='course',
            name='file11',
            field=models.FileField(blank=True, null=True, upload_to='practices/'),
        ),
        migrations.AddField(
            model_name='course',
            name='file12',
            field=models.FileField(blank=True, null=True, upload_to='practices/'),
        ),
        migrations.AddField(
            model_name='course',
            name='file13',
            field=models.FileField(blank=True, null=True, upload_to='practices/'),
        ),
        migrations.AddField(
            model_name='course',
            name='file14',
            field=models.FileField(blank=True, null=True, upload_to='practices/'),
        ),
        migrations.AddField(
            model_name='course',
            name='file15',
            field=models.FileField(blank=True, null=True, upload_to='practices/'),
        ),
        migrations.AddField(
            model_name='course',
            name='file16',
            field=models.FileField(blank=True, null=True, upload_to='practices/'),
        ),
        migrations.AddField(
            model_name='course',
            name='file17',
            field=models.FileField(blank=True, null=True, upload_to='practices/'),
        ),
        migrations.AddField(
            model_name='course',
            name='file18',
            field=models.FileField(blank=True, null=True, upload_to='practices/'),
        ),
        migrations.AddField(
            model_name='course',
            name='file19',
            field=models.FileField(blank=True, null=True, upload_to='practices/'),
        ),
        migrations.AddField(
            model_name='course',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='practices/'),
        ),
        migrations.AddField(
            model_name='course',
            name='file20',
            field=models.FileField(blank=True, null=True, upload_to='practices/'),
        ),
        migrations.AddField(
            model_name='course',
            name='file3',
            field=models.FileField(blank=True, null=True, upload_to='practices/'),
        ),
        migrations.AddField(
            model_name='course',
            name='file4',
            field=models.FileField(blank=True, null=True, upload_to='practices/'),
        ),
        migrations.AddField(
            model_name='course',
            name='file5',
            field=models.FileField(blank=True, null=True, upload_to='practices/'),
        ),
        migrations.AddField(
            model_name='course',
            name='file6',
            field=models.FileField(blank=True, null=True, upload_to='practices/'),
        ),
        migrations.AddField(
            model_name='course',
            name='file7',
            field=models.FileField(blank=True, null=True, upload_to='practices/'),
        ),
        migrations.AddField(
            model_name='course',
            name='file8',
            field=models.FileField(blank=True, null=True, upload_to='practices/'),
        ),
        migrations.AddField(
            model_name='course',
            name='file9',
            field=models.FileField(blank=True, null=True, upload_to='practices/'),
        ),
        migrations.AddField(
            model_name='course',
            name='title_lekcture',
            field=models.CharField(default=1, max_length=255, verbose_name='описание лекций'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Lecture',
        ),
        migrations.DeleteModel(
            name='Practice',
        ),
    ]
